steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'VITE_APP_MODE=live'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kieran-janin-web-staging:$COMMIT_SHA'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kieran-janin-web-staging:$COMMIT_SHA']

  # Deploy container image to Cloud Run (Staging Service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kieran-janin-web-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kieran-janin-web-staging:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/kieran-janin-web-staging:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
